apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgB7vAlFRJqjSpxSdaGMpdZtbdfJx34yPu+i0qpi3K9EoFUrNzVHuvJdPDDfOESvj/Ikr0jh7NpLuzfoYE+oqEuOzAbMfXjc5Iq5JayBbdVacs1LESdrzz+bhQRBxvTPMCHfupAmf8UDuanrR8VH8bpDSKrnzsSPockf7fMtRwZG9HSN6TycA8yvXayK6YfLsVyj1wS8f3sD+pbcXggwqhC8JqKdGx1jSVx6vOogdXaEfl0bWZMRIpVxyATz71pX9fdHG0qhWoGb2wH0rV9atBMlXbz6okonrTU9HQHFU2I9gLT2glH3xFn1fILc9qj1PyYMwfJzJckZWyO3W+WTZIjvKqQbORCeJbC0+zszqL4yHSvujlhEl03ClZc+5cYpxzYzkhSVehlTTyhYPfeLt3Hs/c/imYzuZLpbvqEtWW1uQCzd9ccKz16Lg1Jp5rKw5VJnXajNllr/NcvVX0lJXC/lGZtQGZOJnKWMTwsNCzlgPB3JPwanJf4sGEiRHTXbrUPUZk4V+KDxefncZ/H4o9jAHQCbRVRWNLy22155vU+N4yVFHNmYhjMBQDPDmfjpOk6Ffy7/wUyldPgiFUPQ1y/fwtO8Z8vFPYs0PR5p0RmtMKjYJD0YP+9pZhHXZnJ7FuU9Gzsubr5X+bvpROBIBJvBsgsz1sHaSQ8M/ndyC7NsTwJ74IkzZS76ISqoIx+eNpnTl9zfE7WqdZ6w5PfUhrKQQ+G6uA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
