apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBvaAI2wbMe+r1U3DusClWV+BQvgzlaDpc1m7Fr1dDlK4B98al4oFeIgOkrmCRovgHboQlRI4VtJLBmrAXLemSyOlRaF1eHLbPz67gTo7qR70q+ySyfZflAxGjOUlnFcZOhCEt1ziHxsvjExUMGLMq2xny2rit/jAxCWZSmULRbsBHGH2QCpDUjzgdvB/toEwDxYEA3YnRmqcgQu86o7R2M/Sdn2GklxJBCddDKNr3GBgCDJBx3Vwd6G+EdKFTy3AFb+mvjDDUg7iK+jGuyAJGN/rZzAU/5+CloTlcoY5BwujqIERWNJogUt0wlVpnDcLXWYvgp4IIvlpzjj0tPmjMsMEzVCRW4+s21N3IhZBdKbrgs0ZFCPK/6thOMMjpqi8fFoGNomKhggBqJzp8uU9nq0bK6V5aqhlv32dvIX/Csq1MtMmyKjR2CNAeLjdYu3g0Jh+ITV4S49gUedDUry8vTi8vmj1IbH7cPambVud8mOFBTjXtLAVZrBZ0U6Ix9/Pg+x2rOnl8j7PyLYW0PlA/Z2gsIlYBXb0+owvpxu7DZKZlhlEAPq/TqB4oPcsSSqIVZp9499PUEH3T0gCxGzxiUkF8FgaUzLgiPN3nWOvOg/yGSbVna1C3Nzwx613ASBb24B4Z4fEPryp0bDmJGoaSEsXDg4J+Ssub2EG1QS6FPcD027loSTIcWXlXgH1mRy7Ot1BdZ3JpiT7L4WYj2hvtFfftcug==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
